services:
  minecraft-server:
    image: "ghcr.io/deckerego/minecraft-synology:synology_pivot"
    ports:
      - "25565:25565"
    environment:
      - "WORLD=world"
      - "MEMORY=2048m"
      - "OPERATOR=Herobrine"
    volumes:
      - /volume1/minecraft/worlds:/srv/worlds
    working_dir: /srv
