services:
  minecraft-server:
    image: "ghcr.io/deckerego/minecraft-synology:1.21.5"
    ports:
      - "25565:25565"
    environment:
      - "WORLD=test"
      - "MEMORY=2048m"
      - "OPERATOR=Herobrine"
    volumes:
      - /volume1/minecraft/test:/srv/test
    working_dir: /srv
